class_name MovementTuning
extends RefCounted


# Authoritative values are fixed-point world units, resource milli-units,
# milliseconds, or scale-1000 ratios. They preserve the proven FLUX grammar.
const COMPATIBILITY_ID: String = "movement-tuning-v8-momentum-chains"
const PLAYER_RADIUS: int = 18_000
const BASE_SPEED: int = 324_000
const ACCELERATION: int = 1_980_000
const DECELERATION: int = 3_000_000
const SPRINT_MULTIPLIER: int = 1280
const COUNTER_STRAFE_MULTIPLIER: int = 1900
const COUNTER_STRAFE_DOT_THRESHOLD: int = -24_000_000
const MOVING_MODE_MINIMUM_SPEED: int = 20_000
const INPUT_BUFFER_MS: int = 180
const VARIABLE_JUMP_MINIMUM_MS: int = 160
const FAST_FALL_EXTRA_TICKS: int = 1
const MOVEMENT_CHAIN_RESET_MS: int = 333
const MOVEMENT_CHAIN_COST_STEP_RATIO: int = 100
const MOVEMENT_CHAIN_MAXIMUM_STEPS: int = 4

const STAMINA_MAXIMUM: int = 112_000
const SPRINT_DRAIN_PER_SECOND: int = 34_000
const STAMINA_RECOVERY_PER_SECOND: int = 27_000
const STAMINA_RECOVERY_DELAY_MS: int = 380

const HOP_COST: int = 28_000
const HOP_SPEED: int = 650_000
const HOP_DURATION_MS: int = 320
const HOP_COOLDOWN_MS: int = 500
const JUMP_SUSTAIN_DRAIN_PER_SECOND: int = 80_000
const HOP_STEERING_PER_SECOND: int = 6_000
const JUMP_INVULNERABILITY_MS: int = 90
const WALL_KICK_SPEED: int = 780_000
const WALL_MEMORY_MS: int = 160
const SAME_WALL_LOCKOUT_MS: int = 220
const WALL_SKIM_COST: int = 18_000
const WALL_SKIM_SPEED: int = 520_000
const WALL_SKIM_DURATION_MS: int = 420
const WALL_SKIM_COOLDOWN_MS: int = 300
const WALL_SKIM_SAME_SURFACE_LOCKOUT_MS: int = 900

const SLOW_MINIMUM_RATIO: int = 250
const SLOW_MAXIMUM_RATIO: int = 1000

const DOUBLE_JUMP_COST: int = 24_000
const DOUBLE_JUMP_SPEED: int = 700_000
const DOUBLE_JUMP_DURATION_MS: int = 200
const AIR_REDIRECT_COST: int = 10_000
const AIR_REDIRECT_BLEND: int = 720

const AIR_DODGE_COST: int = 28_000
const AIR_DODGE_SPEED: int = 860_000
const AIR_DODGE_DURATION_MS: int = 180
const AIR_DODGE_COOLDOWN_MS: int = 620
const AIR_DODGE_INVULNERABILITY_MS: int = 120
const ROLL_COST: int = 24_000
const ROLL_SPEED: int = 620_000
const ROLL_DURATION_MS: int = 240
const ROLL_COOLDOWN_MS: int = 520
const ROLL_INVULNERABILITY_MS: int = 130
const WAVE_DASH_INPUT_WINDOW_MS: int = 85
const WAVE_DASH_MINIMUM_TURN: int = 280_000
const WAVE_DASH_SPEED: int = 740_000
const WAVE_DASH_DURATION_MS: int = 240
const WAVE_DASH_STEERING: int = 200

const LANDING_WINDOW_MS: int = 110
const LANDING_CUT_MULTIPLIER: int = 1180
const LANDING_HOP_INTENSITY: int = 680
const LANDING_DOUBLE_JUMP_INTENSITY: int = 820
const LANDING_SLIDE_JUMP_INTENSITY: int = 1000
const LANDING_WALL_KICK_INTENSITY: int = 880
const LANDING_FAST_FALL_BONUS: int = 180
const LANDING_AIR_DODGE_INTENSITY: int = 900
const LANDING_WALL_SKIM_INTENSITY: int = 620
const IMPACT_INFLUENCE_PER_SECOND: int = 1200
const IMPACT_RECOVERY_DURATION_MS: int = 220
const IMPACT_RECOVERY_SPEED_RETENTION: int = 420
const IMPACT_RECOVERY_DECELERATION: int = 2_400_000
const IMPACT_RECOVERY_TECH_COST: int = 18_000
const IMPACT_RECOVERY_TECH_SPEED: int = 360_000
const IMPACT_RECOVERY_INTENSITY: int = 960
const SLIDE_INVULNERABILITY_MS: int = 50
const LANDING_INPUT_BUFFER_MS: int = 80
const WALL_CONTACT_TOLERANCE: int = 3000
const MATERIAL_MOTION_ENABLED: bool = false
const SLIDE_COST: int = 22_000
const SLIDE_ENTRY_SPEED: int = 250_000
const SLIDE_SPEED: int = 720_000
const SLIDE_DURATION_MS: int = 480
const SLIDE_MINIMUM_MS: int = 150
const SLIDE_SUSTAIN_DRAIN_PER_SECOND: int = 45_000
const SLIDE_COOLDOWN_MS: int = 780
const SLIDE_STEERING: int = 320
const SLIDE_JUMP_COST: int = 20_000
const SLIDE_JUMP_SPEED: int = 790_000
const SLIDE_JUMP_DURATION_MS: int = 230
const SLIDE_JUMP_WINDOW_MS: int = 110

const VAULT_COST: int = 14_000
const VAULT_APPROACH: int = 42_000
const VAULT_LANDING: int = 22_000
const VAULT_MAXIMUM_DEPTH: int = 96_000
const VAULT_DURATION_MS: int = 300
const VAULT_COOLDOWN_MS: int = 500
const VAULT_CREST_START_MS: int = 100
const VAULT_CREST_END_MS: int = 230
const SUPERGLIDE_COST: int = 26_000
const SUPERGLIDE_SPEED: int = 900_000
const SUPERGLIDE_DURATION_MS: int = 220

const MAX_AUTHORED_SPEED: int = SUPERGLIDE_SPEED


static func compatibility_hash() -> String:
	return CanonicalContent.sha256({
		"id": COMPATIBILITY_ID,
		"ordinary": [
			PLAYER_RADIUS, BASE_SPEED, ACCELERATION, DECELERATION,
			SPRINT_MULTIPLIER, COUNTER_STRAFE_MULTIPLIER,
			COUNTER_STRAFE_DOT_THRESHOLD, MOVING_MODE_MINIMUM_SPEED,
			INPUT_BUFFER_MS, VARIABLE_JUMP_MINIMUM_MS, FAST_FALL_EXTRA_TICKS,
			MOVEMENT_CHAIN_RESET_MS, MOVEMENT_CHAIN_COST_STEP_RATIO,
			MOVEMENT_CHAIN_MAXIMUM_STEPS,
		],
		"stamina": [
			STAMINA_MAXIMUM, SPRINT_DRAIN_PER_SECOND,
			STAMINA_RECOVERY_PER_SECOND, STAMINA_RECOVERY_DELAY_MS,
		],
		"hop_wall": [
			HOP_COST, HOP_SPEED, HOP_DURATION_MS, HOP_COOLDOWN_MS,
			JUMP_SUSTAIN_DRAIN_PER_SECOND,
			HOP_STEERING_PER_SECOND,
			JUMP_INVULNERABILITY_MS,
			WALL_KICK_SPEED, WALL_MEMORY_MS, SAME_WALL_LOCKOUT_MS,
			WALL_SKIM_COST, WALL_SKIM_SPEED, WALL_SKIM_DURATION_MS,
			WALL_SKIM_COOLDOWN_MS, WALL_SKIM_SAME_SURFACE_LOCKOUT_MS,
		],
		"air": [
			SLOW_MINIMUM_RATIO, SLOW_MAXIMUM_RATIO, DOUBLE_JUMP_COST,
			DOUBLE_JUMP_SPEED, DOUBLE_JUMP_DURATION_MS, AIR_REDIRECT_COST,
			AIR_REDIRECT_BLEND, AIR_DODGE_COST, AIR_DODGE_SPEED,
			AIR_DODGE_DURATION_MS, AIR_DODGE_COOLDOWN_MS,
			AIR_DODGE_INVULNERABILITY_MS, ROLL_COST, ROLL_SPEED,
			ROLL_DURATION_MS, ROLL_COOLDOWN_MS, ROLL_INVULNERABILITY_MS,
			WAVE_DASH_INPUT_WINDOW_MS, WAVE_DASH_MINIMUM_TURN,
			WAVE_DASH_SPEED, WAVE_DASH_DURATION_MS, WAVE_DASH_STEERING,
		],
		"landing": [
			LANDING_WINDOW_MS, LANDING_CUT_MULTIPLIER,
			LANDING_HOP_INTENSITY, LANDING_DOUBLE_JUMP_INTENSITY,
			LANDING_SLIDE_JUMP_INTENSITY, LANDING_WALL_KICK_INTENSITY,
			LANDING_FAST_FALL_BONUS, LANDING_AIR_DODGE_INTENSITY,
			LANDING_WALL_SKIM_INTENSITY,
		],
		"impact": [
			IMPACT_INFLUENCE_PER_SECOND, IMPACT_RECOVERY_DURATION_MS,
			IMPACT_RECOVERY_SPEED_RETENTION, IMPACT_RECOVERY_DECELERATION,
			IMPACT_RECOVERY_TECH_COST, IMPACT_RECOVERY_TECH_SPEED,
			IMPACT_RECOVERY_INTENSITY,
		],
		"movement_revision": [SLIDE_INVULNERABILITY_MS, LANDING_INPUT_BUFFER_MS, WALL_CONTACT_TOLERANCE, MATERIAL_MOTION_ENABLED, SurfaceMotionPolicy.COMPATIBILITY_ID],
		"slide": [
			SLIDE_COST, SLIDE_ENTRY_SPEED, SLIDE_SPEED, SLIDE_DURATION_MS,
			SLIDE_MINIMUM_MS, SLIDE_SUSTAIN_DRAIN_PER_SECOND,
			SLIDE_COOLDOWN_MS, SLIDE_STEERING, SLIDE_JUMP_COST,
			SLIDE_JUMP_SPEED, SLIDE_JUMP_DURATION_MS, SLIDE_JUMP_WINDOW_MS,
		],
		"vault": [
			VAULT_COST, VAULT_APPROACH, VAULT_LANDING, VAULT_MAXIMUM_DEPTH,
			VAULT_DURATION_MS, VAULT_COOLDOWN_MS, VAULT_CREST_START_MS,
			VAULT_CREST_END_MS, SUPERGLIDE_COST, SUPERGLIDE_SPEED,
			SUPERGLIDE_DURATION_MS, MAX_AUTHORED_SPEED,
		],
	})
